### ISSUE TITLE
Adding @islands/prism module break 

### ISSUE THREAD

**Issue by YuukanOO** [ElMassimo/iles#104]
[troubleshooting section]: https://iles-docs.netlify.app/faqs/troubleshooting

- [x] I have read the __[troubleshooting section]__ before opening an issue.
- [x] I have tried upgrading `iles` and `vite`.

### Description 📖

Tested on a fresh project after a clean init. When activating the `@islands/prism` module in the `iles.config.ts` and adding an `mdx` file with some code in it, it fails with a `[plugin:iles:mdx:compile] Cannot handle unknown node raw` error.

### Reproduction 🐞

Tested with this repo: https://github.com/YuukanOO/iles-app

```
$ npm init iles@next
$ cd iles-app
$ npm install
```

Add  `@islands/prism` in the modules section on the iles.config.ts and a sample .mdx file with code in it:

```mdx
---
title: Testing PrismJS
category: tips
---

Hehe

```js
const a = 5;
```

```
$ npm run dev
```

<details>
<summary>Dependencies Info</summary>

_Run `npx iles info` and `pnpm list` (or `npm list`) and provide the output:_

```
iles v0.7.32 vite v2.8.6
```

```
iles-app@0.0.0 /Users/julien/Documents/Sources/tmp/iles-app
├── @islands/prism@0.1.1
├── iles@0.7.32
├── typescript@4.6.2
└── vue-tsc@0.29.8
```

</details>

### Logs 📜

<details>
<summary>Output</summary>

```
18:33:13 [vite] Internal server error: Cannot handle unknown node `raw`
  Plugin: iles:mdx:compile
  File: /Users/julien/Documents/Sources/tmp/iles-app/src/pages/something.mdx
      at Object.unknown (file:///Users/julien/Documents/Sources/tmp/iles-app/node_modules/hast-util-to-estree/index.js:155:9)
      at Object.one [as handle] (file:///Users/julien/Documents/Sources/tmp/iles-app/node_modules/zwitch/index.js:52:17)
      at all (file:///Users/julien/Documents/Sources/tmp/iles-app/node_modules/hast-util-to-estree/index.js:583:28)
      at Object.root (file:///Users/julien/Documents/Sources/tmp/iles-app/node_modules/hast-util-to-estree/index.js:508:20)
      at Object.one [as handle] (file:///Users/julien/Documents/Sources/tmp/iles-app/node_modules/zwitch/index.js:52:17)
      at toEstree (file:///Users/julien/Documents/Sources/tmp/iles-app/node_modules/hast-util-to-estree/index.js:119:24)
      at file:///Users/julien/Documents/Sources/tmp/iles-app/node_modules/xdm/lib/plugin/rehype-recma.js:15:20
      at wrapped (file:///Users/julien/Documents/Sources/tmp/iles-app/node_modules/trough/index.js:115:27)
      at next (file:///Users/julien/Documents/Sources/tmp/iles-app/node_modules/trough/index.js:65:23)
      at done (file:///Users/julien/Documents/Sources/tmp/iles-app/node_modules/trough/index.js:148:7)
```
</details>

### Screenshots 📷

![image](https://user-images.githubusercontent.com/939842/158652247-d6777e78-6d56-40b5-9fbc-f86c4a2f0544.png)

**Comment by ElMassimo** [comment]
Hi Julien, thanks for reporting and providing a reproduction! 😃 

Released [a fix](https://github.com/ElMassimo/iles/commit/844060f00aa6ed94b848d03ef5ca2cfb365c19e1) in `@islands/mdx@0.7.6`.

You can run `npm update` to bump that package, which should fix the error.

**Comment by YuukanOO** [comment]
Nice! Thanks for being so fast! 😉
