### ISSUE TITLE
Version 0.8.0 won't run or build in Windows

### ISSUE THREAD

**Issue by and-Zmei** [ElMassimo/iles#161]
[troubleshooting section]: https://iles-docs.netlify.app/faqs/troubleshooting

- [x] I have read the __[troubleshooting section]__ before opening an issue.
- [x] I have tried upgrading `iles` and `vite`.

### Description 📖

When updating to a new version, the generator does not start in development mode and does not build the project. The default project was launched via the pnpm create iles@next command. Screenshots below...

### Reproduction 🐞

_Please provide a link to a repo that can reproduce the problem you ran into._

<details>
<summary>Dependencies Info</summary>

_Run `npx iles info` and `pnpm list` (or `npm list`) and provide the output:_

```

D:\WORK\ANThill\temp\testIles>npx iles info
iles v0.8.0 vite v3.0.0

D:\WORK\ANThill\temp\testIles>npm list
testiles@0.0.0 D:\WORK\ANThill\temp\testIles
├── iles@0.8.0
├── typescript@4.7.4
└── vue-tsc@0.38.5
```
</details>

### Screenshots 📷

![image](https://user-images.githubusercontent.com/6105225/179192013-edfd1a80-0163-4251-a0ce-2f5de016ab3b.png)
![image](https://user-images.githubusercontent.com/6105225/179192413-c2ad9b75-9112-4ba9-a9f2-fb35109fdddf.png)

**Comment by dhruvkb** [comment]
I tried making a fresh iles app using 
```
pnpm create iles@0.8.0
```
and was not able to reproduce your error.

**Comment by ohuu** [comment]
I hit this problem a couple days ago. I'm also on Windows. Happy to lend a hand.

**Comment by ElMassimo** [comment]
A copy of the trace, or opening the chunk where the error occurs so that we can pinpoint where the issue is happening would definitely help 😃

**Comment by ohuu** [comment]
Here's the trace

```
iles v0.8.0 vite v3.0.1 dev server running at:

  ➜  Local:   http://localhost:5173/
  ➜  Network: use --host to expose
10:48:20 [vite] ✨ new dependencies optimized: graphql-request
10:48:20 [vite] ✨ optimized dependencies changed. reloading
10:48:21 [vite] Internal server error: Missing "./dist/hydration.js" export in "@islands/hydration" package
      at bail (file:///C:/Users/Oliver/Workspace/duet3d-2/storefront-iles/node_modules/vite/dist/node/chunks/dep-10d8d214.js:33603:8)
      at resolve (file:///C:/Users/Oliver/Workspace/duet3d-2/storefront-iles/node_modules/vite/dist/node/chunks/dep-10d8d214.js:33680:10)
      at resolveExports (file:///C:/Users/Oliver/Workspace/duet3d-2/storefront-iles/node_modules/vite/dist/node/chunks/dep-10d8d214.js:34417:12)
      at resolveDeepImport (file:///C:/Users/Oliver/Workspace/duet3d-2/storefront-iles/node_modules/vite/dist/node/chunks/dep-10d8d214.js:34435:31)
      at tryNodeResolve (file:///C:/Users/Oliver/Workspace/duet3d-2/storefront-iles/node_modules/vite/dist/node/chunks/dep-10d8d214.js:34160:20)
      at Context.resolveId (file:///C:/Users/Oliver/Workspace/duet3d-2/storefront-iles/node_modules/vite/dist/node/chunks/dep-10d8d214.js:33897:32)
      at Object.resolveId (file:///C:/Users/Oliver/Workspace/duet3d-2/storefront-iles/node_modules/vite/dist/node/chunks/dep-10d8d214.js:35209:55)
      at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
      at async Context.resolve (file:///C:/Users/Oliver/Workspace/duet3d-2/storefront-iles/node_modules/vite/dist/node/chunks/dep-10d8d214.js:34974:23)
      at async Object.resolveId (file:///C:/Users/Oliver/Workspace/duet3d-2/storefront-iles/node_modules/vite/dist/node/chunks/dep-10d8d214.js:35209:32)
10:48:21 [vite] Internal server error: Missing "./dist/vue.js" export in "@islands/hydration" package
      at bail (file:///C:/Users/Oliver/Workspace/duet3d-2/storefront-iles/node_modules/vite/dist/node/chunks/dep-10d8d214.js:33603:8)
      at resolve (file:///C:/Users/Oliver/Workspace/duet3d-2/storefront-iles/node_modules/vite/dist/node/chunks/dep-10d8d214.js:33680:10)
      at resolveExports (file:///C:/Users/Oliver/Workspace/duet3d-2/storefront-iles/node_modules/vite/dist/node/chunks/dep-10d8d214.js:34417:12)
      at resolveDeepImport (file:///C:/Users/Oliver/Workspace/duet3d-2/storefront-iles/node_modules/vite/dist/node/chunks/dep-10d8d214.js:34435:31)
      at tryNodeResolve (file:///C:/Users/Oliver/Workspace/duet3d-2/storefront-iles/node_modules/vite/dist/node/chunks/dep-10d8d214.js:34160:20)
      at Context.resolveId (file:///C:/Users/Oliver/Workspace/duet3d-2/storefront-iles/node_modules/vite/dist/node/chunks/dep-10d8d214.js:33897:32)
      at Object.resolveId (file:///C:/Users/Oliver/Workspace/duet3d-2/storefront-iles/node_modules/vite/dist/node/chunks/dep-10d8d214.js:35209:55)
      at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
      at async Context.resolve (file:///C:/Users/Oliver/Workspace/duet3d-2/storefront-iles/node_modules/vite/dist/node/chunks/dep-10d8d214.js:34974:23)
      at async Object.resolveId (file:///C:/Users/Oliver/Workspace/duet3d-2/storefront-iles/node_modules/vite/dist/node/chunks/dep-10d8d214.js:35209:32)
```

Here is an excerpt of the code in `chunks/dep-10d8d214.js` which is causing the problem. I've highlighted the line from the trace (35209)

```js
async resolveId(rawId, importer = join$2(root, 'index.html'), options) {
    const skip = options?.skip;
    const ssr = options?.ssr;
    const scan = !!options?.scan;
    const ctx = new Context();
    ctx.ssr = !!ssr;
    ctx._scan = scan;
    ctx._resolveSkips = skip;
    const resolveStart = isDebug ? performance.now() : 0;
    let id = null;
    const partial = {};
    for (const plugin of plugins) {
        if (!plugin.resolveId)
            continue;
        if (skip?.has(plugin))
            continue;
        ctx._activePlugin = plugin;
        const pluginResolveStart = isDebug ? performance.now() : 0;
        const result = await plugin.resolveId.call(ctx, rawId, importer, { // line 35209
            custom: options?.custom,
            isEntry: !!options?.isEntry,
            ssr,
            scan
        });
        if (!result)
            continue;
        if (typeof result === 'string') {
            id = result;
        }
        else {
            id = result.id;
            Object.assign(partial, result);
        }
        isDebug &&
            debugPluginResolve(timeFrom(pluginResolveStart), plugin.name, prettifyUrl(id, root));
        // resolveId() is hookFirst - first non-null result is returned.
        break;
    }
    if (isDebug && rawId !== id && !rawId.startsWith(FS_PREFIX)) {
        const key = rawId + id;
        // avoid spamming
        if (!seenResolves[key]) {
            seenResolves[key] = true;
            debugResolve(`${timeFrom(resolveStart)} ${picocolors.exports.cyan(rawId)} -> ${picocolors.exports.dim(id)}`);
        }
    }
    if (id) {
        partial.id = isExternalUrl(id) ? id : normalizePath$3(id);
        return partial;
    }
    else {
        return null;
    }
},
```

**Comment by ElMassimo** [comment]
This is great @ohuu! I'll check to make sure `file://` is cross-platform compatible, and cut a new release with this patch.

**Comment by ElMassimo** [comment]
Thanks @ohuu, released [a patch](https://github.com/ElMassimo/iles/pull/163) in `iles@0.8.1`.

**Comment by ohuu** [comment]
Just tried it and it seems to be working well. Glad to be of help 👍
