### ISSUE TITLE
Reference Error "performance" with starter duing the build

### ISSUE THREAD

**Issue by ziopod** [ElMassimo/iles#7]
After fresh new install:
~~~
$ pnpm init iles@next
$ cd my-project
$ pnpm i
$ pnpm build
~~~

I got this error:
~~~
iles v0.2.2 vite v2.6.7
build error:
 ReferenceError: performance is not defined
    at withSpinner (/Volumes/vite/iles/node_modules/.pnpm/iles@0.2.2/node_modules/iles/dist/node/chunk-O4XPOHQQ.js:6:21)
    at build (/Volumes/vite/iles/node_modules/.pnpm/iles@0.2.2/node_modules/iles/dist/node/chunk-SPI2F72X.js:27:61)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
 ELIFECYCLE  Command failed with exit code 1.
~~~

My environment: 
- Macosx 10.12.6
- Node v14.16.1

**Comment by ElMassimo** [comment]
Thanks for reporting!

It seems related with Node 14, where `performance` is not globally available.

Releasing a patch soon.
