### ISSUE TITLE
`client:*` directives cannot be used with Pug templating language.

### ISSUE THREAD

**Issue by luminarious** [ElMassimo/iles#83]
[troubleshooting section]: https://iles-docs.netlify.app/faqs/troubleshooting

- [*] I have read the __[troubleshooting section]__ before opening an issue.
- [*] I have tried upgrading `iles` and `vite`.

### Description 📖

`client:*` directives cannot be used with Pug templating language.

### Reproduction 🐞

https://stackblitz.com/edit/iles-dy6fcn?file=src/pages/index.vue
None of the GrowButtons are recognized as islands.

**Comment by luminarious** [comment]
Stackblitz runs dev mode by default, have to manually stop and run `npm run build && npm run preview`

**Comment by ElMassimo** [comment]
Currently, in order to detect hydration directives the framework is using the output of `parse` from `@vue/compiler-sfc`, [checking whether a node has a property that matches a `client:` directive](https://github.com/ElMassimo/iles/blob/main/packages/iles/src/node/plugin/wrap.ts#L84-L85).

For Pug templates, `@vue/compiler-sfc` will [parse the template as text](https://github.com/vuejs/core/blob/main/packages/compiler-sfc/src/parse.ts#L136-L145) (instead of html nodes), which means the current algorithm does not have the necessary data to work with.

---

I'm open to adding support for `pug`, as long as it doesn't affect performance for other use cases.

It's likely that it will require using the `pug` engine to parse the template content and obtain an AST or some kind of tree, which allows traversing the nodes to detect hydration directives, to then [wrap those nodes inside an `Island`](https://github.com/ElMassimo/iles/blob/main/packages/iles/src/node/plugin/wrap.ts#L150-L158).

Let me know if you are interested in exploring this, contributions are welcome!

**Comment by luminarious** [comment]
I wish I could be of any help there, but parsing and compilation are so far outside my comfort zone 😅

Would it be possible to add the entire Island component manually, instead of using the attribute?

**Comment by luminarious** [comment]
This sounds very good, but somehow still fails:
```console
Could not resolve entry module (calendar_ile-1).
✖ building islands bundle
build error:
 Error: Could not resolve entry module (calendar_ile-1).
    at error (C:\Code\hardi.design\iles\node_modules\.pnpm\rollup@2.67.1\node_modules\rollup\dist\shared\rollup.js:160:30)
    at ModuleLoader.loadEntryModule (C:\Code\hardi.design\iles\node_modules\.pnpm\rollup@2.67.1\node_modules\rollup\dist\shared\rollup.js:22416:20)
    at async Promise.all (index 1) {
  code: 'UNRESOLVED_ENTRY',
  watchFiles: [
    'C:/Code/hardi.design/iles/src/components/Calendar.vue',
    'C:/Code/hardi.design/iles/src/components/Calendar.vue?vue&type=template&lang.js',
    'C:/Code/hardi.design/iles/src/components/Calendar.vue?vue&type=style&index=0&scoped=true&lang.stylus',
    'plugin-vue:export-helper',
    'C:/Code/hardi.design/iles/node_modules/.pnpm/@vue+runtime-dom@3.2.30/node_modules/@vue/runtime-dom/dist/runtime-dom.esm-bundler.js'
  ]
}
[!] Error: unfinished hook action(s) on exit:
(vite:css) transform "C:/Code/hardi.design/iles/src/components/Calendar.vue?vue&type=style&index=0&scoped=true&lang.stylus"
(vite:load-fallback) load "C:/Code/hardi.design/iles/node_modules/.pnpm/@vue+runtime-dom@3.2.30/node_modules/@vue/runtime-dom/dist/runtime-dom.esm-bundler.js"
```

To be fair, a generic ClientLoad wrapper component would also be a wonderful alternative to the client:load attribute.
